data <- read.table("household_power_consumption.txt",header=TRUE, sep=";")
subdata <- subset(data, as.Date(data$Date, format="%d/%m/%Y") %in% as.Date(c("2007-02-01", "2007-02-02"), format="%Y-%m-%d"))
subdata$date_time <- strptime(paste(subdata$Date,subdata$Time), "%d/%m/%Y%H:%M:%S")
png(filename = "plot2.png", width = 480, height = 480)
plot(subdata$date_time, as.numeric(as.character(subdata$Global_active_power)), type="l", ylab="Global Active Power (kilowatts)", xlab="")
par()
dev.off()